echo "› vscode/install.sh"

code --install-extension 2gua.rainbow-brackets
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension DotJoshJohnson.xml
code --install-extension LaurentTreguier.uncrustify
code --install-extension PeterJausovec.vscode-docker
code --install-extension dracula-theme.theme-dracula
code --install-extension fallenwood.vimL
code --install-extension hnw.vscode-auto-open-markdown-preview
code --install-extension mitaki28.vscode-clang
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension naereen.makefiles-support-for-vscode
code --install-extension tomphilbin.gruvbox-themes
code --install-extension twxs.cmake
code --install-extension vscodevim.vim
code --install-extension wayou.vscode-todo-highlight
code --install-extension xaver.clang-format
