#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle --ignore-failures -v

echo "› installing topics"
# find the installers and run them iteratively
find . -name install.sh | while read installer ; do
    echo "${installer}";
    sh -c "${installer}" ;
done

echo "› brew cleanup and doctor"
brew update
brew upgrade
brew prune
brew cleanup
brew doctor
